# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98d8da23572a6ab7f7ab646a41ff0d2272645888702b04d09b8dd2ce1fff3088cd5c9174aa9d761ec1ae83257d646c6d4059402959f04c5566b3f7d891f9ec2c

test:
  secret_key_base: e602de8bb01d4fbd873d5f55ca0325525435a4b12a702ffe17c28c71ac1b4593027d4c3a3cf5a0ede27f6c6bb76eea70d3b43e8cd13048f09fc2755ae75b4e79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
